//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _354_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancerType_Symptom
    {
        public int Cancer_Sym_ID { get; set; }
        public int CancerType_ID { get; set; }
        public int Sym_ID { get; set; }
        public string Cancer_Sym_Name { get; set; }
        public string Cancer_Sym_Description { get; set; }
    
        public virtual CancerType CancerType { get; set; }
        public virtual Symptom Symptom { get; set; }
    }
}
