//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _354_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lung_LifeEntities2 : DbContext
    {
        public Lung_LifeEntities2()
            : base("name=Lung_LifeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administration> Administrations { get; set; }
        public virtual DbSet<CancerType> CancerTypes { get; set; }
        public virtual DbSet<CancerType_Symptom> CancerType_Symptom { get; set; }
        public virtual DbSet<CancerTypeTreatment> CancerTypeTreatments { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Medical_Aid> Medical_Aid { get; set; }
        public virtual DbSet<Prevention> Preventions { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<Treatment_Type> Treatment_Type { get; set; }
        public virtual DbSet<User_Access> User_Access { get; set; }
        public virtual DbSet<User_Medication> User_Medication { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Userr> Userrs { get; set; }
    }
}
