//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _354_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treatment()
        {
            this.CancerTypeTreatments = new HashSet<CancerTypeTreatment>();
        }
    
        public int Treat_ID { get; set; }
        public int Treat_Type_ID { get; set; }
        public string Treat_Name { get; set; }
        public string Treat_Description { get; set; }
        public string Treat_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancerTypeTreatment> CancerTypeTreatments { get; set; }
        public virtual Treatment_Type Treatment_Type { get; set; }
    }
}
