//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _354_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Access
    {
        public int User_Access_ID { get; set; }
        public int Admin_ID { get; set; }
        public int User_Role_ID { get; set; }
        public int User_IDs { get; set; }
    
        public virtual Administration Administration { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
