//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _354_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Userr()
        {
            this.Medical_Aid = new HashSet<Medical_Aid>();
            this.User_Medication = new HashSet<User_Medication>();
        }
    
        public int User_IDs { get; set; }
        public string User_Names { get; set; }
        public string User_Surname { get; set; }
        public string User_Email { get; set; }
        public string User_Gender { get; set; }
        public int User_Age { get; set; }
        public byte[] User_Image { get; set; }
        public string User_Username { get; set; }
        public string User_Password { get; set; }
        public int Journal_ID { get; set; }
    
        public virtual Journal Journal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Aid> Medical_Aid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Medication> User_Medication { get; set; }
    }
}
